name: npd

services:
  db:
    extends:
      file: compose.yml
      service: db
    environment:
      POSTGRES_DB: npd_test

  db-migrations:
    extends:
      file: compose.yml
      service: db-migrations
    environment:
      FLYWAY_URL: jdbc:postgresql://${NPD_DB_HOST:-db}:${NPD_DB_PORT:-5432}/npd_test
    volumes: !override
      - ./flyway/sql/django_migrations:/flyway/sql/django_migrations
      - ./flyway/sql/django_reference_data:/flyway/sql/django_reference_data
      - ./flyway/sql/migrations:/flyway/sql/migrations
      - ./flyway/sql/reference_data:/flyway/sql/reference_data

  django-web:
    extends:
      file: compose.yml
      service: django-web
    environment:
      NPD_DB_NAME: npd_test
      TESTING: True
    depends_on: !override
      - db
      - db-migrations
      - valkey
    command: python manage.py runserver 0.0.0.0:8008
    ports:
      - "8008:8008" 

volumes:
  postgres_data:
