name: npd

# by using `compose.test.yml` alone with `docker compose -f compose.test.yml and
# the `extends:` settings for each of the named services, we can merge these
# service definitions cleanly with the ones that already exist in the base
# compose.yml file

services:
  db:
    extends:
      file: compose.yml
      service: db
    environment:
      POSTGRES_DB: npd_test

  db-migrations:
    extends:
      file: compose.yml
      service: db-migrations
    environment:
      FLYWAY_URL: jdbc:postgresql://${NPD_DB_HOST:-db}:${NPD_DB_PORT:-5432}/npd_test
    volumes: !override
      - ./flyway/sql/django_migrations:/flyway/sql/django_migrations
      - ./flyway/sql/django_reference_data:/flyway/sql/django_reference_data
      - ./flyway/sql/migrations:/flyway/sql/migrations
      - ./flyway/sql/reference_data:/flyway/sql/reference_data

  django-web:
    environment:
    build:
      context: ./backend
    container_name: npd
    env_file:
      - path: .env
        required: false
    entrypoint: [] # Don't run collectstatic in entrypoint.sh
    command: python manage.py runserver --insecure 0.0.0.0:8000
    environment:
      NPD_DB_NAME: npd_test
      TESTING: True
      NPD_DJANGO_SECRET: ${NPD_DJANGO_SECRET:-_pth2#=k8-wf-_^t%2))it+3..8la^@@97^#ock7.v=@792w7}
      DEBUG: ${DEBUG:-True}
      DJANGO_LOGLEVEL: ${DJANGO_LOGLEVEL:-INFO}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS:-localhost,127.0.0.1,0.0.0.0}
      NPD_DB_ENGINE: ${NPD_DB_ENGINE:-django.contrib.gis.db.backends.postgis}
      NPD_DB_NAME: ${NPD_DB_NAME:-npd_development}
      NPD_DB_USER: ${NPD_DB_USER:-postgres}
      NPD_DB_PASSWORD: ${NPD_DB_PASSWORD:-postgres}
      NPD_DB_HOST: ${NPD_DB_HOST:-db}
      NPD_DB_PORT: ${NPD_DB_PORT:-5432}
      NPD_REQUIRE_AUTHENTICATION: False
    ports:
      - '8000:8000'
    volumes:
      - './backend/:/app'
      - ./backend/artifacts:/app/artifacts:rw
      - ./backend/provider_directory/static:/app/provider_directory/static:rw
    depends_on:
      - db
      - db-migrations

volumes:
  postgres_data:
