/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type FhirComments = string | string[] | null;
/**
 * The logical id of the resource, as used in the URL for the resource. Once assigned, this value never changes.
 */
export type LogicalIdOfThisArtifact = string | null;
/**
 * A reference to a set of rules that were followed when the resource was constructed, and which must be understood when processing the content. Often, this is a reference to an implementation guide that defines the special rules along with other profiles etc.
 */
export type ASetOfRulesUnderWhichThisContentWasCreated = string | null;
/**
 * The base language in which the resource is written.
 */
export type LanguageOfTheResourceContent = string | null;
/**
 * These resources do not have an independent existence apart from the resource that contains them - they cannot be identified independently, and nor can they have their own independent transaction scope.
 */
export type ContainedInlineResources = unknown[] | null;
/**
 * May be used to represent additional information that is not part of the basic definition of the resource. To make the use of extensions safe and manageable, there is a strict set of governance  applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension.
 */
export type AdditionalContentDefinedByImplementations = unknown[] | null;
/**
 * May be used to represent additional information that is not part of the basic definition of the resource and that modifies the understanding of the element that contains it and/or the understanding of the containing element's descendants. Usually modifier elements provide negation or qualification. To make the use of extensions safe and manageable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer is allowed to define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension. Applications processing a resource are required to check for modifier extensions.  Modifier extensions SHALL NOT change the meaning of any elements on Resource or DomainResource (including cannot change the meaning of modifierExtension itself).
 */
export type ExtensionsThatCannotBeIgnored = unknown[] | null;
/**
 * The uri that describes the actual end-point to connect to.
 */
export type TheTechnicalBaseAddressForConnectingToThisEndpoint = string | null;
/**
 * Contact details for a human to contact about the subscription. The primary use of this for system administrator troubleshooting.
 */
export type ContactDetailsForSourceEGTroubleshooting = unknown[] | null;
/**
 * Additional headers / information to send as part of the notification.
 */
export type UsageDependsOnTheChannelType = (string | null)[] | null;
export type ExtensionFieldForHeader = unknown[] | null;
/**
 * Identifier for the organization that is used to identify the endpoint across multiple disparate systems.
 */
export type IdentifiesThisEndpointAcrossMultipleSystems = unknown[] | null;
/**
 * A friendly name that this endpoint can be referred to with.
 */
export type ANameThatThisEndpointCanBeIdentifiedBy = string | null;
/**
 * The mime type to send the payload in - e.g. application/fhir+xml, application/fhir+json. If the mime type is not specified, then the sender could send any content (including no content depending on the connectionType).
 */
export type MimetypeToSendIfNotSpecifiedTheContentCouldBeAnythingIncludingNoPayloadIfTheConnectionTypeDefinedThis =
  | (string | null)[]
  | null;
export type ExtensionFieldForPayloadMimeType = unknown[] | null;
/**
 * The payload type describes the acceptable content that can be communicated on the endpoint.
 */
export type TheTypeOfContentThatMayBeUsedAtThisEndpointEGXDSDischargeSummaries = unknown[];
/**
 * active | suspended | error | off | test.
 */
export type ActiveSuspendedErrorOffEnteredInErrorTest = string | null;

/**
 * Disclaimer: Any field name ends with ``__ext`` doesn't part of
 * Resource StructureDefinition, instead used to enable Extensibility feature
 * for FHIR Primitive Data Types.
 *
 * The technical details of an endpoint that can be used for electronic
 * services.
 * The technical details of an endpoint that can be used for electronic
 * services, such as for web services providing XDS.b or a REST endpoint for
 * another FHIR server. This may include any security context information.
 */
export interface Endpoint {
  fhir_comments?: FhirComments;
  id?: LogicalIdOfThisArtifact;
  implicitRules?: ASetOfRulesUnderWhichThisContentWasCreated;
  _implicitRules?: unknown;
  language?: LanguageOfTheResourceContent;
  _language?: unknown;
  meta?: unknown;
  contained?: ContainedInlineResources;
  extension?: AdditionalContentDefinedByImplementations;
  modifierExtension?: ExtensionsThatCannotBeIgnored;
  text?: unknown;
  address?: TheTechnicalBaseAddressForConnectingToThisEndpoint;
  _address?: unknown;
  connectionType: ProtocolProfileStandardToBeUsedWithThisEndpointConnection;
  contact?: ContactDetailsForSourceEGTroubleshooting;
  header?: UsageDependsOnTheChannelType;
  _header?: ExtensionFieldForHeader;
  identifier?: IdentifiesThisEndpointAcrossMultipleSystems;
  managingOrganization?: unknown;
  name?: ANameThatThisEndpointCanBeIdentifiedBy;
  _name?: unknown;
  payloadMimeType?: MimetypeToSendIfNotSpecifiedTheContentCouldBeAnythingIncludingNoPayloadIfTheConnectionTypeDefinedThis;
  _payloadMimeType?: ExtensionFieldForPayloadMimeType;
  payloadType: TheTypeOfContentThatMayBeUsedAtThisEndpointEGXDSDischargeSummaries;
  period?: unknown;
  status?: ActiveSuspendedErrorOffEnteredInErrorTest;
  _status?: unknown;
}
/**
 * A coded value that represents the technical details of the usage of this endpoint, such as what WSDLs should be used in what way. (e.g. XDS.b/DICOM/cds-hook).
 */
export interface ProtocolProfileStandardToBeUsedWithThisEndpointConnection {
  [k: string]: unknown;
}
