/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type FhirComments = string | string[] | null
/**
 * May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and manageable, there is a strict set of governance  applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension.
 */
export type AdditionalContentDefinedByImplementations = unknown[] | null
/**
 * Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces.
 */
export type UniqueIdForInterElementReferencing = string | null
/**
 * Source of the definition for the extension code - a logical name or a URL.
 */
export type IdentifiesTheMeaningOfTheExtension = string | null
/**
 * Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).
 */
export type ValueOfExtension4 = string | null
/**
 * Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).
 */
export type ValueOfExtension5 = boolean | null
/**
 * Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).
 */
export type ValueOfExtension6 = string | null
/**
 * Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).
 */
export type ValueOfExtension7 = string | null
/**
 * Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).
 */
export type ValueOfExtension16 = string | null
/**
 * Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).
 */
export type ValueOfExtension17 = string | null
/**
 * Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).
 */
export type ValueOfExtension18 = number | string | null
/**
 * Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).
 */
export type ValueOfExtension24 = string | null
/**
 * Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).
 */
export type ValueOfExtension26 = string | null
/**
 * Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).
 */
export type ValueOfExtension27 = number | null
/**
 * Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).
 */
export type ValueOfExtension28 = string | null
/**
 * Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).
 */
export type ValueOfExtension30 = string | null
/**
 * Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).
 */
export type ValueOfExtension33 = number | null
/**
 * Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).
 */
export type ValueOfExtension42 = string | null
/**
 * Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).
 */
export type ValueOfExtension43 = string | null
/**
 * Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).
 */
export type ValueOfExtension46 = number | null
/**
 * Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).
 */
export type ValueOfExtension47 = string | null
/**
 * Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).
 */
export type ValueOfExtension48 = string | null
/**
 * Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).
 */
export type ValueOfExtension50 = string | null

/**
 * Disclaimer: Any field name ends with ``__ext`` doesn't part of
 * Resource StructureDefinition, instead used to enable Extensibility feature
 * for FHIR Primitive Data Types.
 *
 * Optional Extensions Element.
 * Optional Extension Element - found in all resources.
 */
export interface Extension {
  fhir_comments?: FhirComments
  extension?: AdditionalContentDefinedByImplementations
  id?: UniqueIdForInterElementReferencing
  url?: IdentifiesTheMeaningOfTheExtension
  valueAddress?: unknown
  valueAge?: unknown
  valueAnnotation?: unknown
  valueAttachment?: unknown
  valueBase64Binary?: ValueOfExtension4
  valueBoolean?: ValueOfExtension5
  valueCanonical?: ValueOfExtension6
  valueCode?: ValueOfExtension7
  valueCodeableConcept?: unknown
  valueCodeableReference?: unknown
  valueCoding?: unknown
  valueContactDetail?: unknown
  valueContactPoint?: unknown
  valueContributor?: unknown
  valueCount?: unknown
  valueDataRequirement?: unknown
  valueDate?: ValueOfExtension16
  valueDateTime?: ValueOfExtension17
  valueDecimal?: ValueOfExtension18
  valueDistance?: unknown
  valueDosage?: unknown
  valueDuration?: unknown
  valueExpression?: unknown
  valueHumanName?: unknown
  valueId?: ValueOfExtension24
  valueIdentifier?: unknown
  valueInstant?: ValueOfExtension26
  valueInteger?: ValueOfExtension27
  valueMarkdown?: ValueOfExtension28
  valueMoney?: unknown
  valueOid?: ValueOfExtension30
  valueParameterDefinition?: unknown
  valuePeriod?: unknown
  valuePositiveInt?: ValueOfExtension33
  valueQuantity?: unknown
  valueRange?: unknown
  valueRatio?: unknown
  valueRatioRange?: unknown
  valueReference?: unknown
  valueRelatedArtifact?: unknown
  valueSampledData?: unknown
  valueSignature?: unknown
  valueString?: ValueOfExtension42
  valueTime?: ValueOfExtension43
  valueTiming?: unknown
  valueTriggerDefinition?: unknown
  valueUnsignedInt?: ValueOfExtension46
  valueUri?: ValueOfExtension47
  valueUrl?: ValueOfExtension48
  valueUsageContext?: unknown
  valueUuid?: ValueOfExtension50
}
