/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type FhirComments = string | string[] | null;
/**
 * The logical id of the resource, as used in the URL for the resource. Once assigned, this value never changes.
 */
export type LogicalIdOfThisArtifact = string | null;
/**
 * A reference to a set of rules that were followed when the resource was constructed, and which must be understood when processing the content. Often, this is a reference to an implementation guide that defines the special rules along with other profiles etc.
 */
export type ASetOfRulesUnderWhichThisContentWasCreated = string | null;
/**
 * The base language in which the resource is written.
 */
export type LanguageOfTheResourceContent = string | null;
/**
 * These resources do not have an independent existence apart from the resource that contains them - they cannot be identified independently, and nor can they have their own independent transaction scope.
 */
export type ContainedInlineResources = unknown[] | null;
/**
 * May be used to represent additional information that is not part of the basic definition of the resource. To make the use of extensions safe and manageable, there is a strict set of governance  applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension.
 */
export type AdditionalContentDefinedByImplementations = unknown[] | null;
/**
 * May be used to represent additional information that is not part of the basic definition of the resource and that modifies the understanding of the element that contains it and/or the understanding of the containing element's descendants. Usually modifier elements provide negation or qualification. To make the use of extensions safe and manageable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer is allowed to define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension. Applications processing a resource are required to check for modifier extensions.  Modifier extensions SHALL NOT change the meaning of any elements on Resource or DomainResource (including cannot change the meaning of modifierExtension itself).
 */
export type ExtensionsThatCannotBeIgnored = unknown[] | null;
export type AListOfAlternateNamesThatTheLocationIsKnownAsOrWasKnownAsInThePast = (string | null)[] | null;
export type ExtensionFieldForAlias = unknown[] | null;
/**
 * A description of when the locations opening ours are different to normal, e.g. public holiday availability. Succinctly describing all possible exceptions to normal site availability as detailed in the opening hours Times.
 */
export type DescriptionOfAvailabilityExceptions = string | null;
/**
 * Description of the Location, which helps in finding or referencing the place.
 */
export type AdditionalDetailsAboutTheLocationThatCouldBeDisplayedAsFurtherInformationToIdentifyTheLocationBeyondItsName =
  string | null;
export type TechnicalEndpointsProvidingAccessToServicesOperatedForTheLocation = unknown[] | null;
export type WhatDaysTimesDuringAWeekIsThisLocationUsuallyOpen = unknown[] | null;
export type UniqueCodeOrNumberIdentifyingTheLocationToItsUsers = unknown[] | null;
/**
 * Indicates whether a resource instance represents a specific location or a class of locations.
 */
export type InstanceKind = string | null;
/**
 * Name of the location as used by humans. Does not need to be unique.
 */
export type NameOfTheLocationAsUsedByHumans = string | null;
/**
 * The status property covers the general availability of the resource, not the current value which may be covered by the operationStatus, or by a schedule/slots if they are configured for the location.
 */
export type ActiveSuspendedInactive = string | null;
/**
 * The contact details of communication devices available at the location. This can include phone numbers, fax numbers, mobile numbers, email addresses and web sites.
 */
export type ContactDetailsOfTheLocation = unknown[] | null;
/**
 * Indicates the type of function performed at the location.
 */
export type TypeOfFunctionPerformed = unknown[] | null;

/**
 * Disclaimer: Any field name ends with ``__ext`` doesn't part of
 * Resource StructureDefinition, instead used to enable Extensibility feature
 * for FHIR Primitive Data Types.
 *
 * Details and position information for a physical place.
 * Details and position information for a physical place where services are
 * provided and resources and participants may be stored, found, contained, or
 * accommodated.
 */
export interface Location {
  fhir_comments?: FhirComments;
  id?: LogicalIdOfThisArtifact;
  implicitRules?: ASetOfRulesUnderWhichThisContentWasCreated;
  _implicitRules?: unknown;
  language?: LanguageOfTheResourceContent;
  _language?: unknown;
  meta?: unknown;
  contained?: ContainedInlineResources;
  extension?: AdditionalContentDefinedByImplementations;
  modifierExtension?: ExtensionsThatCannotBeIgnored;
  text?: unknown;
  address?: unknown;
  alias?: AListOfAlternateNamesThatTheLocationIsKnownAsOrWasKnownAsInThePast;
  _alias?: ExtensionFieldForAlias;
  availabilityExceptions?: DescriptionOfAvailabilityExceptions;
  _availabilityExceptions?: unknown;
  description?: AdditionalDetailsAboutTheLocationThatCouldBeDisplayedAsFurtherInformationToIdentifyTheLocationBeyondItsName;
  _description?: unknown;
  endpoint?: TechnicalEndpointsProvidingAccessToServicesOperatedForTheLocation;
  hoursOfOperation?: WhatDaysTimesDuringAWeekIsThisLocationUsuallyOpen;
  identifier?: UniqueCodeOrNumberIdentifyingTheLocationToItsUsers;
  managingOrganization?: unknown;
  mode?: InstanceKind;
  _mode?: unknown;
  name?: NameOfTheLocationAsUsedByHumans;
  _name?: unknown;
  operationalStatus?: unknown;
  partOf?: unknown;
  physicalType?: unknown;
  position?: unknown;
  status?: ActiveSuspendedInactive;
  _status?: unknown;
  telecom?: ContactDetailsOfTheLocation;
  type?: TypeOfFunctionPerformed;
}
