/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type FhirComments = string | string[] | null;
/**
 * The logical id of the resource, as used in the URL for the resource. Once assigned, this value never changes.
 */
export type LogicalIdOfThisArtifact = string | null;
/**
 * A reference to a set of rules that were followed when the resource was constructed, and which must be understood when processing the content. Often, this is a reference to an implementation guide that defines the special rules along with other profiles etc.
 */
export type ASetOfRulesUnderWhichThisContentWasCreated = string | null;
/**
 * The base language in which the resource is written.
 */
export type LanguageOfTheResourceContent = string | null;
/**
 * These resources do not have an independent existence apart from the resource that contains them - they cannot be identified independently, and nor can they have their own independent transaction scope.
 */
export type ContainedInlineResources = unknown[] | null;
/**
 * May be used to represent additional information that is not part of the basic definition of the resource. To make the use of extensions safe and manageable, there is a strict set of governance  applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension.
 */
export type AdditionalContentDefinedByImplementations = unknown[] | null;
/**
 * May be used to represent additional information that is not part of the basic definition of the resource and that modifies the understanding of the element that contains it and/or the understanding of the containing element's descendants. Usually modifier elements provide negation or qualification. To make the use of extensions safe and manageable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer is allowed to define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension. Applications processing a resource are required to check for modifier extensions.  Modifier extensions SHALL NOT change the meaning of any elements on Resource or DomainResource (including cannot change the meaning of modifierExtension itself).
 */
export type ExtensionsThatCannotBeIgnored = unknown[] | null;
export type WhetherThisPractitionerRoleRecordIsInActiveUse = boolean | null;
/**
 * A description of site availability exceptions, e.g. public holiday availability. Succinctly describing all possible exceptions to normal site availability as details in the available Times and not available Times.
 */
export type DescriptionOfAvailabilityExceptions = string | null;
/**
 * A collection of times the practitioner is available or performing this role at the location and/or healthcareservice.
 */
export type TimesTheServiceSiteIsAvailable = unknown[] | null;
/**
 * Roles which this practitioner is authorized to perform for the organization.
 */
export type RolesWhichThisPractitionerMayPerform = unknown[] | null;
export type TechnicalEndpointsProvidingAccessToServicesOperatedForThePractitionerWithThisRole = unknown[] | null;
export type TheListOfHealthcareServicesThatThisWorkerProvidesForThisRoleSOrganizationLocationS = unknown[] | null;
export type BusinessIdentifiersThatAreSpecificToARoleLocation = unknown[] | null;
export type TheLocationSAtWhichThisPractitionerProvidesCare = unknown[] | null;
/**
 * The practitioner is not available or performing this role during this period of time due to the provided reason.
 */
export type NotAvailableDuringThisTimeDueToProvidedReason = unknown[] | null;
export type SpecificSpecialtyOfThePractitioner = unknown[] | null;
export type ContactDetailsThatAreSpecificToTheRoleLocationService = unknown[] | null;

/**
 * Disclaimer: Any field name ends with ``__ext`` doesn't part of
 * Resource StructureDefinition, instead used to enable Extensibility feature
 * for FHIR Primitive Data Types.
 *
 * Roles/organizations the practitioner is associated with.
 * A specific set of Roles/Locations/specialties/services that a practitioner
 * may perform at an organization for a period of time.
 */
export interface PractitionerRole {
  fhir_comments?: FhirComments;
  id?: LogicalIdOfThisArtifact;
  implicitRules?: ASetOfRulesUnderWhichThisContentWasCreated;
  _implicitRules?: unknown;
  language?: LanguageOfTheResourceContent;
  _language?: unknown;
  meta?: unknown;
  contained?: ContainedInlineResources;
  extension?: AdditionalContentDefinedByImplementations;
  modifierExtension?: ExtensionsThatCannotBeIgnored;
  text?: unknown;
  active?: WhetherThisPractitionerRoleRecordIsInActiveUse;
  _active?: unknown;
  availabilityExceptions?: DescriptionOfAvailabilityExceptions;
  _availabilityExceptions?: unknown;
  availableTime?: TimesTheServiceSiteIsAvailable;
  code?: RolesWhichThisPractitionerMayPerform;
  endpoint?: TechnicalEndpointsProvidingAccessToServicesOperatedForThePractitionerWithThisRole;
  healthcareService?: TheListOfHealthcareServicesThatThisWorkerProvidesForThisRoleSOrganizationLocationS;
  identifier?: BusinessIdentifiersThatAreSpecificToARoleLocation;
  location?: TheLocationSAtWhichThisPractitionerProvidesCare;
  notAvailable?: NotAvailableDuringThisTimeDueToProvidedReason;
  organization?: unknown;
  period?: unknown;
  practitioner?: unknown;
  specialty?: SpecificSpecialtyOfThePractitioner;
  telecom?: ContactDetailsThatAreSpecificToTheRoleLocationService;
}
