/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type FhirComments = string | string[] | null;
/**
 * May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and manageable, there is a strict set of governance  applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension.
 */
export type AdditionalContentDefinedByImplementations = unknown[] | null;
/**
 * Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces.
 */
export type UniqueIdForInterElementReferencing = string | null;
/**
 * Plain text narrative that identifies the resource in addition to the resource reference.
 */
export type TextAlternativeForTheResource = string | null;
/**
 * A reference to a location at which the other resource is found. The reference may be a relative reference, in which case it is relative to the service base URL, or an absolute URL that resolves to the location where the resource is found. The reference may be version specific or not. If the reference is not to a FHIR RESTful server, then it should be assumed to be version specific. Internal fragment references (start with '#') refer to contained resources.
 */
export type LiteralReferenceRelativeInternalOrAbsoluteURL = string | null;
/**
 * The expected type of the target of the reference. If both Reference.type and Reference.reference are populated and Reference.reference is a FHIR URL, both SHALL be consistent.  The type is the Canonical URL of Resource Definition that is the type this reference refers to. References are URLs that are relative to http://hl7.org/fhir/StructureDefinition/ e.g. "Patient" is a reference to http://hl7.org/fhir/StructureDefinition/Patient. Absolute URLs are only allowed for logical models (and can only be used in references in logical models, not resources).
 */
export type TypeTheReferenceRefersToEGPatient = string | null;

/**
 * Disclaimer: Any field name ends with ``__ext`` doesn't part of
 * Resource StructureDefinition, instead used to enable Extensibility feature
 * for FHIR Primitive Data Types.
 *
 * A reference from one resource to another.
 */
export interface Reference {
  fhir_comments?: FhirComments;
  extension?: AdditionalContentDefinedByImplementations;
  id?: UniqueIdForInterElementReferencing;
  display?: TextAlternativeForTheResource;
  _display?: unknown;
  identifier?: unknown;
  reference?: LiteralReferenceRelativeInternalOrAbsoluteURL;
  _reference?: unknown;
  type?: TypeTheReferenceRefersToEGPatient;
  _type?: unknown;
}
